site_name: Mall Docs
nav:
  - Home: 'index.md'
  - User: 
    - Main: './user/user.md'
  - Mall: 
    - 首页: './mall/index.md'    
    - 优惠券: './mall/coupon.md'    
    - 产品: './mall/goods.md'    
    - 搜索: './mall/search.md'    
    - 购物车: './mall/cart.md'
    - 地址: './mall/address.md'    
    - 活动: './mall/activity.md'    
